apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: nn3wt8vmv-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nn3wt8vmv-go 
  name: nn3wt8vmv-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: nn3wt8vmv-go 
